/*
 * MTMR0_config.h
 *
 *  Created on: Nov 30, 2024
 *      Author: Asteroid
 */

#ifndef MTMR0_CONFIG_H_
#define MTMR0_CONFIG_H_
/* Mode Selection */
/* Options: */
/* 	1. PRIVATE_TMR0_MODE_NORMAL
	2. PRIVATE_TMR0_MODE_PHASE_CORRECT_PWM
	3. PRIVATE_TMR0_MODE_CTC
	4. PRIVATE_TMR0_MODE_FAST_PWM			*/

#define MTMR0_MODE												PRIVATE_TMR0_MODE_NORMAL


/* Select Compare Output Mode (Non-PWM) */
/* Options: */
/* 	1. PRIVATE_TMR0_NON_PWM_CM_OUTPUT_MODE_OC0_DISCONNECTED
	2. PRIVATE_TMR0_NON_PWM_CM_OUTPUT_MODE_TOGGLE_OC0_ON_CM
	3. PRIVATE_TMR0_NON_PWM_CM_OUTPUT_MODE_CLEAR_OC0_ON_CM
	4. PRIVATE_TMR0_NON_PWM_CM_OUTPUT_MODE_SET_OC0_ON_CM		*/

#define MTMR0_NON_PWM_CM_OUTPUT_MODE_OC0						PRIVATE_TMR0_NON_PWM_CM_OUTPUT_MODE_OC0_DISCONNECTED


/* Select Compare Output Mode (Fast-PWM) */
/* Options: */
/* 	1. PRIVATE_TMR0_FAST_PWM_CM_OUTPUT_MODE_OC0_DISCONNECTED
	2. PRIVATE_TMR0_FAST_PWM_CM_OUTPUT_MODE_RESERVED
	3. PRIVATE_TMR0_FAST_PWM_CM_OUTPUT_MODE_OC0_CLR_ON_CM_SET_AT_TOP
	4. PRIVATE_TMR0_FAST_PWM_CM_OUTPUT_MODE_OC0_SET_ON_CM_CLR_AT_TOP	*/

#define MTMR0_FAST_PWM_CM_OUTPUT_MODE_OC0						PRIVATE_TMR0_FAST_PWM_CM_OUTPUT_MODE_OC0_DISCONNECTED


/* Select Compare Output Mode (Phase Correct PWM) */
/* Options: */
/* 	1. PRIVATE_TMR0_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC0_DISCONNECTED
	2. PRIVATE_TMR0_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_RESERVED
	3. PRIVATE_TMR0_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC0_CLR_UP_SET_DOWN
	4. PRIVATE_TMR0_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC0_SET_UP_CLR_DOWN	*/

#define MTMR0_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC0				PRIVATE_TMR0_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC0_DISCONNECTED




/* Select Clock Prescaler */
/* Options: */
/* 	1. PRIVATE_TMR0_CLK_NO_CLK_SRC
	2. PRIVATE_TMR0_CLK_NO_PRESCALER
	3. PRIVATE_TMR0_CLK_PRESCALER_8
	4. PRIVATE_TMR0_CLK_PRESCALER_64
	5. PRIVATE_TMR0_CLK_PRESCALER_256
	6. PRIVATE_TMR0_CLK_PRESCALER_1024
    7. PRIVATE_TMR0_CLK_EXT_CLK_ON_T0_FALLING
    8. PRIVATE_TMR0_CLK_EXT_CLK_ON_T0_RISING 		*/

#define MTMR0_CLK_PRESCALER										PRIVATE_TMR0_CLK_PRESCALER_8











#endif /* MTMR0_CONFIG_H_ */
