/* LIB Layer */
#include "../LIB/bit_math.h"
#include "../LIB/std_types.h"
#include "MTMR1_config.h"
#include "MTMR1_interface.h"
#include "MTMR1_private.h"


/******************          Timer 1           ********************/

static void (*MTMR1_Pvoid_OVF_FunctionPtr)(void) = STD_TYPE_NULL;
static void (*MTMR1_Pvoid_CMA_FunctionPtr)(void) = STD_TYPE_NULL;
static void (*MTMR1_Pvoid_CMB_FunctionPtr)(void) = STD_TYPE_NULL;

void MTMR1_Init(){
	/* Select Mode */
#if MTMR1_MODE == PRIVATE_TMR1_MODE_NORMAL || MIMR1_ICU_ENABLE
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_8BIT
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_9BIT
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_10BIT
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_CTC_TOP_OCR1A
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_FAST_PWM_8BIT
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_FAST_PWM_9BIT
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_FAST_PWM_10BIT
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_PWM_PHASE_FREQ_CORRECT_TOP_ICR1
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_PWM_PHASE_FREQ_CORRECT_TOP_OCR1A
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_TOP_ICR1
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_TOP_OCR1A
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_CTC_TOP_ICR1
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_FAST_PWM_TOP_ICR1
	CLR_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#elif MTMR1_MODE == PRIVATE_TMR1_MODE_FAST_PWM_TOP_OCR1A
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM10);
	SET_BIT(PRIVATE_TCCR1A, PRIVATE_TCCR1A_WGM11);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM12);
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_WGM13);

#endif

	/* Select Compare Output Mode On OC1A and OC1B */
switch(MTMR1_MODE){
	case PRIVATE_TMR1_MODE_NORMAL:
	case PRIVATE_TMR1_MODE_CTC_TOP_OCR1A:
	case PRIVATE_TMR1_MODE_CTC_TOP_ICR1:

		PRIVATE_TCCR1A |= MTMR1_NON_PWM_CM_OUTPUT_MODE_OC1A;
		PRIVATE_TCCR1A |= MTMR1_NON_PWM_CM_OUTPUT_MODE_OC1B;
		break;

	case PRIVATE_TMR1_MODE_FAST_PWM_8BIT:
	case PRIVATE_TMR1_MODE_FAST_PWM_9BIT:
	case PRIVATE_TMR1_MODE_FAST_PWM_10BIT:
	case PRIVATE_TMR1_MODE_FAST_PWM_TOP_ICR1:
	case PRIVATE_TMR1_MODE_FAST_PWM_TOP_OCR1A:

		PRIVATE_TCCR1A |= MTMR1_FAST_PWM_CM_OUTPUT_MODE_OC1A;
		PRIVATE_TCCR1A |= MTMR1_FAST_PWM_CM_OUTPUT_MODE_OC1B;
		break;

	case PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_8BIT:
	case PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_9BIT:
	case PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_10BIT:
	case PRIVATE_TMR1_MODE_PWM_PHASE_FREQ_CORRECT_TOP_ICR1:
	case PRIVATE_TMR1_MODE_PWM_PHASE_FREQ_CORRECT_TOP_OCR1A:
	case PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_TOP_ICR1:
	case PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_TOP_OCR1A:

		PRIVATE_TCCR1A |= MTMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1A;
		PRIVATE_TCCR1A |= MTMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1B;
		break;

}

	/* ICU Init */
#if MIMR1_ICU_ENABLE
	/* Select Rising edge to trigger capture event */
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_ICES1);

	/* Enable ICU Noise Canceler */
	SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_ICNC1);

#endif

	/* Select CLK Prescaler */
	PRIVATE_TCCR1B |= MTMR1_CLK_PRESCALER;


}
void MTMR1_setPreload(u16 Copy_u16PreloadValue){
	PRIVATE_TCNT1 = Copy_u16PreloadValue;
}

void MTMR1_Interrupt(Timer1_Modes Copy_TimerMode, TMR1_Interrupt_Mode Copy_IntMode){

	switch (Copy_TimerMode){
		case MTMR1_OVF:
			switch(Copy_IntMode){
				case MTMR1_Enable:
					SET_BIT(PRIVATE_TIMSK, PRIVATE_TIMSK_TOIE1);
					break;
				case MTMR1_Disable:
					CLR_BIT(PRIVATE_TIMSK, PRIVATE_TIMSK_TOIE1);
					break;
			}
			break;
		case MTMR1_CTC_A:
			switch(Copy_IntMode){
				case MTMR1_Enable:
					SET_BIT(PRIVATE_TIMSK, PRIVATE_TIMSK_OCIE1A);
					break;
				case MTMR1_Disable:
					CLR_BIT(PRIVATE_TIMSK, PRIVATE_TIMSK_OCIE1A);
					break;
			}
			break;
		case MTMR1_CTC_B:
			switch(Copy_IntMode){
				case MTMR1_Enable:
					SET_BIT(PRIVATE_TIMSK, PRIVATE_TIMSK_OCIE1B);
					break;
				case MTMR1_Disable:
					CLR_BIT(PRIVATE_TIMSK, PRIVATE_TIMSK_OCIE1B);
					break;
			}
	}
}

void MTMR1_voidSet_OCR1A_Value(u16 Copy_u16_OCR1A_Value){
	PRIVATE_OCR1A = Copy_u16_OCR1A_Value;
}
void MTMR1_voidSet_OCR1B_value(u16 Copy_u16_OCR1B_Value){
	PRIVATE_OCR1B = Copy_u16_OCR1B_Value;
}
void MTMR1_voidSet_ICR1_value(u16 Copy_u16_ICR1_Value){
	PRIVATE_ICR1 = Copy_u16_ICR1_Value;
}
void MTMR1_OVF_SetCallback(void (*Copy_PvoidFuncPtr)(void)){
	MTMR1_Pvoid_OVF_FunctionPtr = Copy_PvoidFuncPtr;
}
void MTMR1_CMA_SetCallback(void (*Copy_PvoidFuncPtr)(void)){
	MTMR1_Pvoid_CMA_FunctionPtr = Copy_PvoidFuncPtr;
}

void MTMR1_CMB_SetCallback(void (*Copy_PvoidFuncPtr)(void)){
	MTMR1_Pvoid_CMB_FunctionPtr = Copy_PvoidFuncPtr;
}

/* Timer1 OVF ISR */
void __vector_9(void)		__attribute__((signal));
void __vector_9(void){
	MTMR1_Pvoid_OVF_FunctionPtr();
}

/* Timer1 Compare Match A  ISR */
void __vector_7(void)		__attribute__((signal));
void __vector_7(void){
	MTMR1_Pvoid_CMA_FunctionPtr();
}

/* Timer1 Compare Match B  ISR */
void __vector_8(void)		__attribute__((signal));
void __vector_8(void){
	MTMR1_Pvoid_CMB_FunctionPtr();
}


/*****************          Timer 1 - ICU         ********************/

static void (*MICU_PvoidFunctionPtr)(void) = STD_TYPE_NULL;


void MICU_voidSelectEdge(MICU_edgeMode Copy_EdgeMode){
	switch(Copy_EdgeMode){
		case MICU_FALLING_EDGE:
			CLR_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_ICES1);
			break;

		case MICU_RISING_EDGE:
			SET_BIT(PRIVATE_TCCR1B, PRIVATE_TCCR1B_ICES1);
			break;
		}
}

void MICU_voidGetICR1Val(u16* Copy_Pu16ICR1Val){
	*Copy_Pu16ICR1Val = PRIVATE_ICR1;
}

void MICU_voidInterruptEnable(){
	SET_BIT(PRIVATE_TIMSK, PRIVATE_TIMSK_TICIE1);
}

void MICU_voidInterruptDisable(){
	CLR_BIT(PRIVATE_TIMSK, PRIVATE_TIMSK_TICIE1);
}

void MICU_voidSetCallBack(void (*Copy_PvoidFuncPtr)(void)){
	MICU_PvoidFunctionPtr = Copy_PvoidFuncPtr;
}

/* Timer1 ICU ISR */
void __vector_6(void)		__attribute__((signal));
void __vector_6(void){
	MICU_PvoidFunctionPtr();
}

