/*
 * MTMR0_config.h
 *
 *  Created on: Nov 30, 2024
 *      Author: Asteroid
 */

#ifndef MTMR1_CONFIG_H_
#define MTMR1_CONFIG_H_


/******************          Timer 1           ********************/

/* Mode Selection */
/* Options: */
/* 	1. 	PRIVATE_TMR1_MODE_NORMAL
	2. 	PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_8BIT
	3. 	PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_9BIT
	4. 	PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_10BIT
    5.  PRIVATE_TMR1_MODE_CTC_TOP_OCR1A
    6.  PRIVATE_TMR1_MODE_FAST_PWM_8BIT
    7.  PRIVATE_TMR1_MODE_FAST_PWM_9BIT
    8.  PRIVATE_TMR1_MODE_FAST_PWM_10BIT
    9.  PRIVATE_TMR1_MODE_PWM_PHASE_FREQ_CORRECT_TOP_ICR1
    10. PRIVATE_TMR1_MODE_PWM_PHASE_FREQ_CORRECT_TOP_OCR1A
    11. PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_TOP_ICR1
    12. PRIVATE_TMR1_MODE_PWM_PHASE_CORRECT_TOP_OCR1A
    13. PRIVATE_TMR1_MODE_CTC_TOP_ICR1
    14. PRIVATE_TMR1_MODE_FAST_PWM_TOP_ICR1
    15. PRIVATE_TMR1_MODE_FAST_PWM_TOP_OCR1A   				*/

#define MTMR1_MODE										PRIVATE_TMR1_MODE_FAST_PWM_TOP_ICR1


/* Select Compare Output Mode on OC1A (Non-PWM) */
/* Options: */
/* 	1. PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_OC1A_DISCONNECTED
	2. PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_TOGGLE_OC1A_ON_CM
	3. PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_CLEAR_OC1A_ON_CM
	4. PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_SET_OC1A_ON_CM		*/

/* Select Compare Output Mode on OC1B (Non-PWM) */
/* Options: */
/* 	1. PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_OC1B_DISCONNECTED
	2. PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_TOGGLE_OC1B_ON_CM
	3. PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_CLEAR_OC1B_ON_CM
	4. PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_SET_OC1B_ON_CM		*/



#define MTMR1_NON_PWM_CM_OUTPUT_MODE_OC1A					PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_OC1A_DISCONNECTED
#define MTMR1_NON_PWM_CM_OUTPUT_MODE_OC1B					PRIVATE_TMR1_NON_PWM_CM_OUTPUT_MODE_OC1B_DISCONNECTED



//* Select Compare Output Mode on OC1A (Fast-PWM) */
/* Options: */
/* 	1. PRIVATE_TMR1_FAST_PWM_CM_OUTPUT_MODE_OC1A_DISCONNECTED
	2. PRIVATE_TMR1_FAST_PWM_CM_OUTPUT_MODE_TOGGLE_OC1A_ON_CM
	3. PRIVATE_TMR1_FAST_PWM_CM_OUTPUT_MODE_OC1A_CLR_ON_CM_SET_AT_TOP
	4. PRIVATE_TMR1_FAST_PWM_CM_OUTPUT_MODE_OC1A_SET_ON_CM_CLR_AT_TOP		*/

/* Select Compare Output Mode on OC1B (Fast-PWM) */
/* Options: */
/* 	1. PRIVATE_TMR1_FAST_PWM_CM_OUTPUT_MODE_OC1B_DISCONNECTED
	2. PRIVATE_TMR1_FAST_PWM_CM_OUTPUT_MODE_OC1B_CLR_ON_CM_SET_AT_TOP
	3. PRIVATE_TMR1_FAST_PWM_CM_OUTPUT_MODE_OC1B_SET_ON_CM_CLR_AT_TOP		*/


#define MTMR1_FAST_PWM_CM_OUTPUT_MODE_OC1A					PRIVATE_TMR1_FAST_PWM_CM_OUTPUT_MODE_OC1A_CLR_ON_CM_SET_AT_TOP
#define MTMR1_FAST_PWM_CM_OUTPUT_MODE_OC1B					PRIVATE_TMR1_FAST_PWM_CM_OUTPUT_MODE_OC1B_CLR_ON_CM_SET_AT_TOP



/* Select Compare Output Mode on OC1A (Phase Correct or Phase & Frequency Correct PWM) */
/* Options: */
/* 	1. PRIVATE_TMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1A_DISCONNECTED
	2. PRIVATE_TMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_TOGGLE_OC1A_ON_CM
	3. PRIVATE_TMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1A_CLR_UP_SET_DOWN
	4. PRIVATE_TMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1A_SET_UP_CLR_DOWN	*/

/* Select Compare Output Mode on OC1B (Phase Correct or Phase & Frequency Correct PWM) */
/* Options: */
/* 	1. PRIVATE_TMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1B_DISCONNECTED
	2. PRIVATE_TMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1B_CLR_UP_SET_DOWN
	3. PRIVATE_TMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1B_SET_UP_CLR_DOWN	*/

#define MTMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1A			PRIVATE_TMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1A_DISCONNECTED
#define MTMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1B			PRIVATE_TMR1_PHASE_FREQ_CORRECT_PWM_CM_OUTPUT_MODE_OC1B_DISCONNECTED



/* Select Clock Prescaler */
/* Options: */
/* 	1. PRIVATE_TMR1_CLK_NO_CLK_SRC
	2. PRIVATE_TMR1_CLK_NO_PRESCALER
	3. PRIVATE_TMR1_CLK_PRESCALER_8
	4. PRIVATE_TMR1_CLK_PRESCALER_64
	5. PRIVATE_TMR1_CLK_PRESCALER_256
	6. PRIVATE_TMR1_CLK_PRESCALER_1024
    7. PRIVATE_TMR1_CLK_EXT_CLK_ON_T0_FALLING
    8. PRIVATE_TMR1_CLK_EXT_CLK_ON_T0_RISING 		*/

#define MTMR1_CLK_PRESCALER								PRIVATE_TMR1_CLK_PRESCALER_64




/*****************          Timer 1 - ICU         ********************/

/* Enable Or Disable Timer1 ICU */
/* Options: */
/* 	1. PRIVATE_ENABLE
	2. PRIVATE_DISABLE */

#define MIMR1_ICU_ENABLE									PRIVATE_DISABLE




#endif /* MTMR1_CONFIG_H_ */
