#ifndef MTMR2_CONFIG_H_
#define MTMR2_CONFIG_H_
/* Mode Selection */
/* Options: */
/* 	1. PRIVATE_TMR2_MODE_NORMAL
	2. PRIVATE_TMR2_MODE_PHASE_CORRECT_PWM
	3. PRIVATE_TMR2_MODE_CTC
	4. PRIVATE_TMR2_MODE_FAST_PWM			*/

#define MTMR2_MODE												PRIVATE_TMR2_MODE_NORMAL


/* Select Compare Output Mode (Non-PWM) */
/* Options: */
/* 	1. PRIVATE_TMR2_NON_PWM_CM_OUTPUT_MODE_OC2_DISCONNECTED
	2. PRIVATE_TMR2_NON_PWM_CM_OUTPUT_MODE_TOGGLE_OC2_ON_CM
	3. PRIVATE_TMR2_NON_PWM_CM_OUTPUT_MODE_CLEAR_OC2_ON_CM
	4. PRIVATE_TMR2_NON_PWM_CM_OUTPUT_MODE_SET_OC2_ON_CM		*/

#define MTMR2_NON_PWM_CM_OUTPUT_MODE_OC2						PRIVATE_TMR2_NON_PWM_CM_OUTPUT_MODE_OC2_DISCONNECTED


/* Select Compare Output Mode (Fast-PWM) */
/* Options: */
/* 	1. PRIVATE_TMR2_FAST_PWM_CM_OUTPUT_MODE_OC2_DISCONNECTED
	2. PRIVATE_TMR2_FAST_PWM_CM_OUTPUT_MODE_RESERVED
	3. PRIVATE_TMR2_FAST_PWM_CM_OUTPUT_MODE_OC2_CLR_ON_CM_SET_AT_TOP
	4. PRIVATE_TMR2_FAST_PWM_CM_OUTPUT_MODE_OC2_SET_ON_CM_CLR_AT_TOP	*/

#define MTMR2_FAST_PWM_CM_OUTPUT_MODE_OC2						PRIVATE_TMR2_FAST_PWM_CM_OUTPUT_MODE_OC2_DISCONNECTED


/* Select Compare Output Mode (Phase Correct PWM) */
/* Options: */
/* 	1. PRIVATE_TMR2_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC2_DISCONNECTED
	2. PRIVATE_TMR2_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_RESERVED
	3. PRIVATE_TMR2_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC2_CLR_UP_SET_DOWN
	4. PRIVATE_TMR2_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC2_SET_UP_CLR_DOWN	*/

#define MTMR2_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC2				PRIVATE_TMR2_PHASE_CORRECT_PWM_CM_OUTPUT_MODE_OC2_DISCONNECTED




/* Select Clock Prescaler */
/* Options: */
/* 	1. PRIVATE_TMR2_CLK_NO_CLK_SRC
	2. PRIVATE_TMR2_CLK_NO_PRESCALER
	3. PRIVATE_TMR2_CLK_PRESCALER_8
	4. PRIVATE_TMR2_CLK_PRESCALER_64
	5. PRIVATE_TMR2_CLK_PRESCALER_256
	6. PRIVATE_TMR2_CLK_PRESCALER_1024
    7. PRIVATE_TMR2_CLK_EXT_CLK_ON_T0_FALLING
    8. PRIVATE_TMR2_CLK_EXT_CLK_ON_T0_RISING 		*/

#define MTMR2_CLK_PRESCALER										PRIVATE_TMR2_CLK_PRESCALER_8











#endif /* MTMR2_CONFIG_H_ */
